yii2/frontend/controllers/OlympiadController.php
<?php

namespace frontend\controllers;

use frontend\components\filters\AccessAdminTeacherFilter;
use frontend\components\filters\AccessUserFilter;
use frontend\models\olympiad\OlympiadExercise;
use frontend\models\olympiad\OlympiadResult;
use frontend\models\Smarty;
use frontend\models\SmartyExample;
use frontend\models\User;
use Mpdf\Tag\Ol;
use Yii;
use frontend\models\olympiad\Olympiad;
use frontend\models\olympiad\OlympiadSearch;
use yii\db\Exception;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OlympiadController implements the CRUD actions for Olympiad model.
 */
class OlympiadController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'save-result' => ['POST'],
                ],
            ],
            'access-admin-teacher' => [
                'class' => AccessAdminTeacherFilter::className(),
                'only' => ['index', 'view', 'create', 'delete', 'publish-olympiad', 'hide-olympiad']
            ],
            'access-user' => [
                'class' => AccessUserFilter::className(),
                'only' => ['list', 'save-result', 'result']
            ]
        ];
    }


    public function actionList() {
        $user = User::findOne(Yii::$app->session->get('login_user'));

        $time = time() - ((24*60*60) - 60);
        $olympiads = Olympiad::find()
            ->where([
                'and',
                [
                    'or',
                    ['=', 'id_user', $user->id_who_learn],
                    ['=', 'id_user', 15]
                ],
                [
                    'and',
                    ['>', 'date', $time],
                    ['=', 'is_public', 1]
                ]
            ])
            ->with('author')
            ->all();

        //Yii::debug($olympiads);

        return $this->render('list', [
            'olympiads' => $olympiads,
            'user' => $user,
        ]);
    }

    public function actionExerciseList($id_olympiad) {
        $user = User::findOne(Yii::$app->session->get('login_user'));

        /*olympiada aktivna i polzovatele est dostup*/
        $is_active = Olympiad::isActive($id_olympiad);
        $is_public = Olympiad::isPublic($id_olympiad, $user->id);
        Yii::debug($is_active, 'is_active');
        Yii::debug($is_public, 'is_public');
        if (!$is_active || !$is_public) {
            Yii::$app->session->setFlash('error', 'Нет доступа олимпиаду!');
            return $this->redirect(['list']);
        }

        /*olimpiada*/
        $olympiad = Olympiad::findOne($id_olympiad);

        return $this->render('exercise-list', [
            'olympiad' => $olympiad,
        ]);
    }

    /*ajax*/
    public function actionSaveResult() {
        $request = Yii::$app->request;

        if ($request->isPost && $request->isAjax) { // ajax i post request
            if (isset(
                $_POST['id_user'],
                $_POST['id_exercise'],
                $_POST['time'],
                $_POST['count_true_answers'],
                $_POST['count_errors'],
                $_POST['simulator_id'],
                $_POST['id_smarty'],
                $_POST['qa']
            )) {
                /*== vse POST peremennie proveryayem ==*/
                $new_olympiad_id_user            = (int) $request->post('id_user');
                $new_olympiad_id_exercise        = (int) $request->post('id_exercise');
                $new_olympiad_time               = (int) $request->post('time');
                $new_olympiad_count_true_answers = (int) $request->post('count_true_answers');
                $new_olympiad_count_errors       = (int) $request->post('count_errors');
                $new_olympiad_simulator_id       = (int) $request->post('simulator_id'); //ne ispolzuetsya
                $new_olympiad_id_smarty          = (int) $request->post('id_smarty');//ne ispolzuetsya
                $new_olympiad_qa                 = $request->post('qa');

                $user = User::findOne(Yii::$app->session->get('login_user'));

                $exercise = OlympiadExercise::findOne($new_olympiad_id_exercise);
                if ($exercise === null || $user->id != $new_olympiad_id_user) throw new NotFoundHttpException(); // esli zadanie net ili polzovatel nepravilniy

                /*== Polzovatele est dostup olimpiade i olimpiade net takoy rezultat zadanie ==*/
                if (
                    Olympiad::isActive($exercise->id_olympiad) &&
                    Olympiad::isPublic($exercise->id_olympiad, $user->id) &&
                    OlympiadResult::findOne(['id_user' => $user->id, 'id_exercise' => $exercise->id]) === null
                ) {
                    /*== Soxranenie rezultata ==*/
                    $newOlympiadResult = new OlympiadResult();
                    $newOlympiadResult->id_user = $user->id;
                    $newOlympiadResult->id_olympiad = $exercise->id_olympiad;
                    $newOlympiadResult->id_exercise = $new_olympiad_id_exercise;
                    $newOlympiadResult->time = $new_olympiad_time;
                    $newOlympiadResult->qa = serialize($new_olympiad_qa);
                    $newOlympiadResult->count_true_answers = $new_olympiad_count_true_answers;
                    $newOlympiadResult->count_errors = $new_olympiad_count_errors;
                    if (!$newOlympiadResult->save()) {
                        throw new Exception('Error!', $newOlympiadResult->errors);
                    }

                    /*== return result link ==*/
                    return '/olympiad/exercise-result?id_olympiad_result=' . $newOlympiadResult->primaryKey;
                }
            }
        }

        throw new NotFoundHttpException();
    }

    public function actionExerciseResult($id_olympiad_result) {

        /**
         * ====Nujno realizovat dostupi========
         */

        $olympiadResult = OlympiadResult::findOne($id_olympiad_result);

        return $this->render('result', [
            'olympiadResult' => $olympiadResult,
        ]);
    }

    /**
     * Lists all Olympiad models.
     * =====Olimpiadu mojno sozdat tolko admin i prepodavateli==========
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OlympiadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /*==dlya publikatsii==*/
    public function actionPublishOlympiad($id_olympiad) {
        $user = User::findOne(Yii::$app->session->get('login_user'));

        $olympiad = Olympiad::findOne(['id' => $id_olympiad]);
        $olympiad->scenario = Olympiad::SCENARIO_PUBLISH;

        // prepodavatel ne mogut opublikovat drugoe olimpiadu
        if ($user->type == 'teacher' && $olympiad !== null && $olympiad->id_user != $user->id) {
            Yii::$app->session->setFlash('error','Нет доступа!');
            return $this->redirect(['index']);
        }
        Yii::debug($olympiad->exercises, 'exercises');
        if ( $olympiad->exercises == null ) {
            Yii::$app->session->setFlash('error','Сначала добавьте задание!');
            return $this->redirect(['index']);
        }
        $olympiad->is_public = 1; // Opublikuem
        if ($olympiad->save()) {

            Yii::$app->session->setFlash('success','Олимпиада успешно опубликован.');
            return $this->redirect(['index']);
        } else {
            Yii::debug($olympiad->errors, 'error db');
            Yii::$app->session->setFlash('warning','Ошибка!');
            return $this->redirect(['index']);
        }
    }

    /*skrit olimpiadu*/
    public function actionHideOlympiad($id_olympiad){
        $user = User::findOne(Yii::$app->session->get('login_user'));

        $olympiad = Olympiad::findOne(['id' => $id_olympiad]);
        $olympiad->scenario = Olympiad::SCENARIO_PUBLISH;

        // prepodavatel ne mogut skrit drugoe olimpiadu
        if ($user->type == 'teacher' && $olympiad !== null && $olympiad->id_user != $user->id) {
            Yii::$app->session->setFlash('error','Нет доступа!');
            return $this->redirect(['index']);
        }
        $olympiad->is_public = 0; // skrivaem
        if ($olympiad->save()) {

            Yii::$app->session->setFlash('info','Операция успешно завершена.');
            return $this->redirect(['index']);
        } else {
            Yii::$app->session->setFlash('warning','Ошибка!');
            return $this->redirect(['index']);
        }
    }

    /**
     * Displays a single Olympiad model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $olympiadExercises = OlympiadExercise::find()->where(['id_olympiad' => $id])->with(['smarty'])->all();

        return $this->render('view', [
            'model' => $this->findModel($id),
            'olympiadExercises' => $olympiadExercises,
        ]);
    }

    /**
     * Creates a new Olympiad model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $user = User::findOne(Yii::$app->session->get('login_user'));
        $newOlympiad = new Olympiad();

        if ($newOlympiad->load(Yii::$app->request->post())) {
            $newOlympiad->id_user = $user->id;
            $newOlympiad->is_public = 0;

            if ($newOlympiad->save()) {
                return $this->redirect(['view', 'id' => $newOlympiad->id]);
            }

            Yii::debug($newOlympiad->errors);
        }

yii2/frontend/views/olympiad/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use vova07\imperavi\Widget;
use kartik\date\DatePicker;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model frontend\models\olympiad\Olympiad */
/* @var $form yii\widgets\ActiveForm */
/* @var $students_IDs array */
/* @var $selected_IDs array */

?>

<div class="olympiad-form col-md-7">

    <?php $form = ActiveForm::begin([
        'options' => ['class' => 'form-horizontal']
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 50,
            'plugins' => [
                'fontfamily',
                'fontcolor',
                'fullscreen',
            ],
        ],
    ]); ?>

    <?= $form->field($model, 'tmp_date')->widget(DatePicker::className(), [
        'name' => 'anniversary',
        'readonly' => true,
        //'value' => date('d-M-y', strtotime('+2 days')),
        'options' => ['placeholder' => 'Выберите ...'],
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'dd.mm.yyyy',
		    'todayHighlight' => true,
            'startDate' => 'd',
        ]
    ]) ?>

    <?php $model->isNewRecord?>

    <?= $form->field($model, 'public_users_ids')->widget(Select2::class,[
        'name' => 'kv-state-240',
        'data' => $students_IDs,
        'theme' => Select2::THEME_KRAJEE,
        'size' => Select2::MEDIUM,
        'options' => [
            'placeholder' => 'Выберите ...',
            'multiple' => true,
            'options' => $model->isNewRecord ? null : $selected_IDs,

        ],
        'pluginOptions' => [
            //'allowClear' => true
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
$cssImperaviToolbar = <<<CSS
.redactor-toolbar {
z-index: 9;
}
CSS;

$this->registerCss($cssImperaviToolbar);

yii2/frontend/views/olympiad/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\olympiad\OlympiadSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="olympiad-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_user') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'is_public') ?>

    <?php // echo $form->field($model, 'public_users_ids') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii2/frontend/views/olympiad/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\olympiad\Olympiad */
/* @var $students_IDs array */

$this->title = 'Создать олимпиаду';
$this->params['breadcrumbs'][] = ['label' => 'Все олимпиады', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="olympiad-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'students_IDs' => $students_IDs,
    ]) ?>

</div>

yii2/frontend/views/olympiad/exercise-list.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 12.09.2018
 * Time: 18:47
 *
 * @var $this \yii\web\View
 * @var $olympiad \frontend\models\olympiad\Olympiad
 */

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;

Url::remember(Url::current(), 'remember-olympiad');

$this->title = 'Задание';
$this->params['breadcrumbs'][] = ['label' => 'Олимпиады', 'url' => 'list'];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row"><!-- Opisanie Olimpiadi -->
    <div class="col-md-6 col-md-offset-3">
        <div class="center-block">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?=$olympiad->name?></h3>
                </div>
                <div class="panel-body">
                    <h4>Описание</h4>
                    <?=HtmlPurifier::process($olympiad->description)?>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr><td>Создатель: </td><td><?=$olympiad->author->fio?></td></tr>
                    </table>
                </div>
                <div class="panel-footer">
                    <a href="<?=Url::to(['/result/olympiad-high-score-table', 'id_olympiad' => $olympiad->id])?>" class="btn btn-default"><span class="glyphicon glyphicon-flag" aria-hidden="true"></span> Результаты</a>
                </div>
            </div>
        </div>
    </div>
</div><!-- Opisanie Olimpiadi -->


<div class="page-header">
    <h2>Задание</h2>
</div>

<div class="row"><!-- Zadanie -->
    <?php foreach ($olympiad->exercises as $exercise): ?>
        <div class="col-md-4">
            <div class="panel panel-default shadow3">
                <div class="panel-heading">
                    <?php
                    $exerciseResult = $exercise->getResult(Yii::$app->session->get('login_user'))->one();
                    Yii::debug($exerciseResult, 'ex-res');
                    ?>
                    <strong>Задание: </strong><?= $exercise->smarty->name ?>
                    <?php if($exerciseResult): ?>
                        <span class="badge pull-right">Пройден</span>
                    <?php else: ?>
                        <span class="badge pull-right">Доступен</span>
                    <?php endif; ?>
                </div>
                <div class="panel-body">
                    <?php if (!$exerciseResult): ?>
                        <?= Html::a('Пройти', Url::to(['/simulator/smarty', 'id_smarty' => $exercise->id_smarty, 't' => 'olympiad', 'id_exercise' => $exercise->id]), [
                            'class' => 'btn btn-primary center-block'
                        ]) ?>
                    <?php else: ?>
                        <?= Html::a('Посмотреть результаты', Url::to(['/olympiad/exercise-result', 'id_olympiad_result' => $exerciseResult->id]), [
                            'class' => 'btn btn-warning center-block'
                        ])?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div><!-- Zadanie -->


<?php

$cssShadowBox = <<<CSS

.shadow3 {
box-shadow: 0 1px 5px rgba(0, 0, 0, 0.15);
}


CSS;

$this->registerCss($cssShadowBox);

yii2/frontend/views/olympiad/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\olympiad\OlympiadSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Все олимпиады';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="olympiad-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать олимпиаду', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'id_user',
            [
                'attribute' => 'id_user',
                'label' => 'Создатель',
                'value' => function($model) {
                    return \frontend\models\User::find()->select(['fio'])->where(['id' => $model->id_user])->scalar();
                }
            ],
            'name',
            //'description:html',
            ['attribute' => 'date', 'format' => ['date', 'php: d-M Y H:i:s (МСК)']],
            ['attribute' => 'created_at', 'format' => ['date', 'php: d-M Y H:i:s (МСК)']],
            //'is_public',
            //'public_users_ids',
            //'created_at',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update} {delete} {add_exercise} {publish} {hide}',
                'buttons' => [
                    'publish' => function($url, $model, $key){
                        return Html::a('Опубликовать', \yii\helpers\Url::to(['/olympiad/publish-olympiad', 'id_olympiad' => $model->id]), ['class' => 'btn btn-success btn-xs']);
                    },
                    'hide' => function($url, $model, $key){
                        return Html::a('Скрыть', \yii\helpers\Url::to(['/olympiad/hide-olympiad', 'id_olympiad' => $model->id]), ['class' => 'btn btn-warning btn-xs']);
                    },
                    'add_exercise' => function($url, $model, $key) {
                        return Html::a('Добавить задание', \yii\helpers\Url::to(['/smarty-manager/create', 'type' => 'olympiad', 'id' => $model->id]), ['class' => 'btn btn-primary btn-xs']);
                    }
                ],
                'visibleButtons' => [
                    'publish' => function ($model, $key, $index){
                        return $model->is_public === 0;
                    },
                    'hide' => function ($model, $key, $index){
                        return $model->is_public === 1;
                    },
                    'add_exercise' => function ($model, $key, $index){
                        return $model->is_public === 0;
                    },
                ]
            ],
        ],
    ]); ?>
</div>

yii2/frontend/views/olympiad/list.php
<?php
/* @var $this yii\web\View */
/* @var $olympiads \frontend\models\Olimp */
/* @var $user \frontend\models\User */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Олимпиады';

$this->params['breadcrumbs'][] = $this->title;
?>

<div class="page-header">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

<?php if ( $olympiads && $user->type == 'student'): ?>
    <div class="row">
        <?php foreach ($olympiads as $olympiad): ?>
            <?php if (in_array($user->id, $olympiad->usersID)): ?>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?= Html::encode($olympiad->name) ?></h3>
                        </div>

                        <table class="table table-bordered">
                            <tr><td>Создатель:</td><td><?= $olympiad->author->fio ?></td></tr>
                            <tr><td>Дата проведения:</td><td><?= Yii::$app->formatter->asDate($olympiad->date) ?></td></tr>
                        </table>
                        <div class="panel-footer">
                            <nav aria-label="...">
                                <?php if($olympiad->date <= time()): ?>
                                    <ul class="pager">
                                        <li><a href="<?= Url::to(['/olympiad/exercise-list', 'id_olympiad' => $olympiad->id]) ?>" >Начать <span aria-hidden="true">&rarr;</span></a></li>
                                    </ul>
                                <?php else: ?>
                                    <p class="text-center text-primary"> <strong>Осталось:</strong></p>
                                    <p class="text-success text-center"><strong><?=Yii::$app->formatter->asDuration($olympiad->date - time())?></strong></p>
                                <?php endif; ?>
                            </nav>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php else: ?>
        <?php if($user->type == 'student'): ?>
            <div class="well">
                <p class="text-info">
                    В данный момент актуальных олимпиад нет.
                </p>
            </div>
        <?php else: ?>
            <div class="well">
                <p class="text-danger">
                    Вы не можете пройти олимпиаду!
                </p>
            </div>
        <?php endif; ?>
<?php endif; ?>

yii2/frontend/views/olympiad/result.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 13.09.2018
 * Time: 18:38
 *
 * @var $this \yii\web\View
 * @var $olympiadResult \frontend\models\olympiad\OlympiadResult
 *
 */

use kartik\rating\StarRating;
use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Результат';
$this->params['breadcrumbs'][] = ['label' => 'Все  олимпиады', 'url' => '/olympiad/list'];
$this->params['breadcrumbs'][] = ['label' => 'Задание', 'url' => Url::previous('remember-olympiad')];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="page-header">
    <h2><?=Html::encode($this->title)?></h2>
</div>

<?php if ($olympiadResult): ?>
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="center-block">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Результат</h3>
                </div>
                <div class="panel-body text-center">
                    <!--<span class="label label-default">Rating: </span>-->
                    <?= StarRating::widget([
                        'name' => 'rating_result',
                        'value' => $olympiadResult->ratingStar,
                        'pluginOptions' => ['displayOnly' => true]
                    ]); ?>
                    <div><strong>Правильно:</strong><span class="text-success"> <?= $olympiadResult->count_true_answers?></span> </div>
                    <div><strong>Ошибки: </strong><span class="text-danger"><?= $olympiadResult->count_errors?></span></div>
                    <div><strong>Потрачено: </strong><?= Yii::$app->formatter->asDuration($olympiadResult->time/1000)?></div>
                </div>
                <div class="panel-footer">
                    <nav aria-label="...">
                        <ul class="pager">
                            <li><a href="<?= Url::previous('remember-olympiad') ?>">Все задания</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

yii2/frontend/views/olympiad/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\olympiad\Olympiad */
/* @var $students_IDs array*/
/* @var $selected_IDs array*/

$this->title = 'Обновить олимпиаду: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Все олимпиады', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>
<div class="olympiad-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'students_IDs' => $students_IDs,
        'selected_IDs' => $selected_IDs,
    ]) ?>

</div>

yii2/frontend/views/olympiad/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\olympiad\Olympiad */
/* @var $olympiadExercises object */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Все олимпиады', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="olympiad-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'author',
            ['label' => 'Создатель', 'value' => $model->author->fio],
            'name',
            'description:html',
//            'date:date',
            ['attribute' => 'date', 'format' => ['date', 'php: d-M Y H:i:s (МСК)']],
            ['attribute' => 'created_at', 'format' => ['date', 'php: d-M Y H:i:s (МСК)']],
//            'is_public',
            ['attribute' => 'is_public', 'label' => 'Является общедоступной','value' => function($model) {return $model->is_public == 1 ? 'Да' : 'Нет';}],
//            'created_at:date',
            //'public_users_ids',
            ['attribute' => 'public_users_ids', 'label' => 'Cписок участников', 'format' => 'html', 'value' => function($model,$widget) {
                $users = $model->users;
                $html = '<ul class="list-group">';
                foreach($users as $user) {
                    $html .= '<li class="list-group-item">';
                    $html .= '<span class="badge">';
                    $html .= $user->type;
                    $html .= '</span>';
                    $html .= $user->fio;
                    $html .= '</li>';
                }
                $html .= '</ul>';

                return $html;
            }]
        ],
    ]) ?>

    <h3 class="page-header">
        Cписок задания
    </h3>
    <?php if ($olympiadExercises): ?>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <th>#</th>
                            <th>Название Smarty</th>
                            <th>Кол-во примеров</th>
                        </tr>
                        <?php
                        $count_exercise = 1;
                        ?>
                        <?php foreach($olympiadExercises as $exercise): ?>
                            <tr>
                                <td><?=$count_exercise++?></td>
                                <td><?=$exercise->smarty->name?></td>
                                <td><?=$exercise->smarty->quantity?></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    <?php else: ?>
        <well>
            <strong>Пусто.</strong>
        </well>
    <?php endif; ?>

</div>