yii2/frontend/models/Simulators.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "simulators".
 *
 * @property int $id
 * @property string $name
 */
class Simulators extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'simulators';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }
}

yii2/frontend/controllers/SimulatorController.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 15.08.2018
 * Time: 15:46
 */

namespace frontend\controllers;

use frontend\components\filters\AccessAdminFilter;
use frontend\models\CourseResult;
use frontend\models\Exercise;
use frontend\models\Mentalmap;
use frontend\models\OlimpExercise;
use frontend\models\OlimpExerciseStatus;
use frontend\models\olympiad\Olympiad;
use frontend\models\olympiad\OlympiadExercise;
use frontend\models\olympiad\OlympiadResult;
use frontend\models\Setting;
use frontend\models\Simulators;
use frontend\models\SimulatorsResults;
use frontend\models\Smarty;
use frontend\models\User;
use Yii;
use yii\db\Exception;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use frontend\components\filters\AccessUserFilter;
use yii\web\JsonResponseFormatter;
use yii\web\NotFoundHttpException;
use kartik\mpdf\Pdf;
use common\models\Jobs;
use yii\web\Response;

class SimulatorController extends Controller {

    public function beforeAction($action)
    {
        if ($action->id == 'save-result') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    public function behaviors()
    {
        return [
            /**  filter dlya, polzovatel avtorizovan ili net. Esli ne avtorizovan dostup zapreshen  */
            'access_user' => [
                'class' => AccessUserFilter::class,
            ],
            /* filter dlya tolko admina */
            'access_admin' => [
                'class' => AccessAdminFilter::class,
                'only' => ['create-smarty'],
            ]
        ];
    }


    public function actionWork ( $id_exercise, $t = 'course') {
        $this->layout = 'work';
        $session = Yii::$app->session;
        if ( $t == 'course' ) {

            if (CourseResult::findOne(['id_user' => $session->get('login_user')])->id_current_exercise != $id_exercise) {
                throw new NotFoundHttpException('Неверний задания');
            }

            /* zadanie */
            $exercise = Exercise::findOne(['id' => $id_exercise]);

            /* nastroyki */
            $settings = Setting::findOne(['id' => $exercise->id_settings]);

            return $this->render('work-start', [
                'settings' => $settings,
                'id_exercise' => $exercise->id,
            ]);
        } elseif ($t == 'olimp') {
            $olimpExerciseStatus = OlimpExerciseStatus::find()->select('is_public')->where(['id_exercise' => $id_exercise, 'id_user' => $session->get('login_user')])->one();

            if ( $olimpExerciseStatus->is_public == 0 || $olimpExerciseStatus->is_end == 1) {
                throw new NotFoundHttpException();
            }

            /* zadanie */
            $exercise = OlimpExercise::findOne(['id' => $id_exercise]);

            if ($exercise->id_simulators == 9) {
                $id_smarty = (int)Setting::find()->select('id_rules')->where(['id' => $exercise->id_settings])->scalar();

                return $this->redirect(['/simulator/smarty', 'id_smarty' => $id_smarty, 'id_exercise' => $exercise->id, 't' => 'olimp']);
            }
            /* nastroyki */
            $settings = Setting::findOne(['id' => $exercise->id_settings]);

            return $this->render('work-start', [
                'settings' => $settings,
                'id_exercise' => $exercise->id,
                'course_type' => $t,
            ]);
        } else {
            throw new NotFoundHttpException();
        }
    }

    public function actionCreateSmarty() {
        $smarty = new \frontend\models\CreateSmartyForm();

        if ($smarty->load(Yii::$app->request->post())) {

            if ($smarty->saveSmarty()) {

                Yii::$app->session->setFlash('success', 'Примеры Smarty сохранен.');

                return $this->redirect(['/smarty-manager']);

            } else {
                Yii::$app->session->addFlash('error', 'Ошибка в валидации.');
            }
        }

        $smarty->name = '';
        $smarty->rows = 2;
        $smarty->quantity = 1;
        $smarty->examples = null;

        return $this->render('create-smarty', [
            'smarty' => $smarty,
        ]);
    }

    public function actionSettings($id_simulators) {

        //poka tolko est nastroyki Smarty (id = 9)
        if ($id_simulators != 9) {
            throw new NotFoundHttpException('Настройка не найдена.');
        }

        // vse primeri trenajor Smarty
        $user = User::findOne(Yii::$app->session->get('login_user'));
        $settings_query = Smarty::find()->where(['id_user' => 15, 'type' => 'simulator']);
        if ($user->type == 'student') {
            $teacher_id = $user->id_who_learn;
            $settings_query->orWhere(['id_user' => $teacher_id, 'type' => 'simulator']);
        }
        if ($user->type == 'teacher') {
            $settings_query->orWhere(['id_user' => $user->id, 'type' => 'simulator']);
        }
        $smarty_settings = $settings_query->with('user')->asArray()->all();
        $settings = ArrayHelper::map($smarty_settings, 'id', 'name', 'user.fio' );
        Yii::debug($settings);
        if (!$settings) {
            Yii::$app->session->setFlash('error', "<strong>Пока примеров нет.</strong>");
        }

        return $this->render('settings', [
            'settings' => $settings,
        ]);
    }

    public function actionSmarty($id_smarty, $t = 'simulator', $id_exercise = 0) {
        $smarty_id = (int)$id_smarty;

        /* esli get parametr ne int, to stranitsa ne naydena */
        if (!is_integer($smarty_id)) {
            throw new NotFoundHttpException('Страница не найдена.');
        }

        /*== esli rezultate takoy zadanie est ili net dostupa==*/
        if ($t == 'olympiad') {
            $user = User::findOne(Yii::$app->session->get('login_user'));
            $exercise = OlympiadExercise::findOne($id_exercise);
            if ( ($olympiadResult = OlympiadResult::findOne(['id_user' => $user->id, 'id_exercise' => $id_exercise])) !== null || $exercise === null || !Olympiad::isPublic($exercise->id_olympiad, $user->id) || !Olympiad::isActive($exercise->id_olympiad)) {
                Yii::$app->session->setFlash('error', 'Нет доступа или задание уже пройден!');
                return $this->redirect(['/olympiad/list']);
            }
        }

        $smarty_examples = Smarty::find()->where(['id' => $smarty_id])->with('examples')->one();

        $examplesArray = [];
        $examplesAnswersArray = [];
        $cnt = 0;
        foreach ($smarty_examples->examples as $ex) {
            $examplesAnswersArray[$cnt] = $ex->answer;
            $examplesArray[$cnt++] = explode('|', $ex->example);
        }

        Yii::debug($examplesAnswersArray);

        Yii::debug(count($smarty_examples->examples));

        Yii::debug($examplesArray);

        return $this->render('smarty', [
            'smarty_examples' => $smarty_examples,
            'examplesArray' => $examplesArray,
            'examplesAnswersArray' => $examplesAnswersArray,
            't' => $t,
            'id_exercise' => $id_exercise,
        ]);
    }

    /*pechat primeri Smarty*/
    public function actionExercisePrint($id_smarty) {
        $this->layout = '';
        // get your HTML raw content without any layouts or scripts
        $content = $this->renderPartial('_exerciseView', ['smarty_id' => $id_smarty]);

        $cssInline =<<<CSS
.kv-heading-1{font-size:18px} .smarty {
    background: rgba(255, 255, 255, 0.7);
}
.smarty td {
    text-align: center;
    font-weight: normal;
    font-size: 1.2em;
}
.smarty td input {
    width:2px !important;
    padding: 0 5px;
    font-size: 1em;
}

.page-header p{
    font-size: 18px;
}
CSS;

        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_LANDSCAPE,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => $cssInline,
            // set mPDF properties on the fly
            'options' => [
                'title' => 'Тренажор Smarty',
                'showWatermarkText' => true,
                "autoScriptToLang" => true,
                "autoLangToFont" => true,
                /*
                'allow_charset_conversion' => true,
                'charset_in' => 'utf-8',*/
            ],
            // call mPDF methods on the fly
            'methods' => [
                'SetHeader'=>['Примеры'],
                'SetFooter'=>['{PAGENO}'],
                'SetWatermarkText' => ['Obrain', 0.3],

            ],
        ]);

        // return the pdf output as per the destination setting
        return $pdf->render();
    }

    public function actionResult($id) {
        $session = Yii::$app->session;

        $sr = SimulatorsResults::findOne(['id' => $id]);

        if (!$sr || $sr->id_user != $session->get('login_user')) {
            throw new NotFoundHttpException('Неверний ползователь');
        }

        return $this->render('result', [
            'simulators_results' => $sr,
        ]);
    }

    /* ajax request */
    public function actionSaveResult() {
        $request = Yii::$app->request;
        $is_isset = false;

        //smarty
        if ($request->post('simulator_id') == 9) {
            $is_isset = isset($_POST['time'])
                && isset($_POST['count_true_answers'])
                && isset($_POST['count_errors'])
                && isset($_POST['simulator_id'])

yii2/frontend/views/simulator/_exerciseView.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 22.08.2018
 * Time: 14:26
 *
 * @var $this \yii\web\View
 * @var $smarty_id int
 */

use frontend\models\Smarty;
use yii\helpers\ArrayHelper;

$smarty_examples = Smarty::find()->where(['id' => $smarty_id])->with('examples')->one();
$examplesArray = [];
$examplesAnswersArray = [];
$cnt = 0;
foreach ($smarty_examples->examples as $ex) {
    $examplesAnswersArray[$cnt] = $ex->answer;
    $examplesArray[$cnt++] = explode('|', $ex->example);
}
?>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<!--    <title>Document</title>-->
</head>
<body>
<div class="page-header">
    <h2>Тренажер Smarty <small>Правила: <?= $smarty_examples->name ?></small></h2>
</div>
<?php
$manyArOne = [];
$tmpArray = array_chunk($examplesArray, 20);

$cnt = 0;
$answer_id = 0;
$cntTmpArray = count($tmpArray);
for ($j = 0; $j < $cntTmpArray; $j++) {
    for ($i = 0; $i < $smarty_examples->rows; $i++) {
        $manyArOne[$cnt++] = '<tr><td>' . implode('</td><td>', ArrayHelper::getColumn($tmpArray[$j], $i)) . '</td></tr>';
    }

    $tmpCount = count($tmpArray[$j]);
    $helperString = '';
    for ($k = 0; $k < $tmpCount; $k++) {
        $helperString .= '<td>' . '<div class="form-group"><input type="text" data-answerid="'. $answer_id++ .'" size="5" class="form-control example-answer"></div>' . '</td>';
    }
    $manyArOne[$cnt++] = '<tr>' . $helperString . '</tr>';
}
?>

<?php
$cntArray = count($tmpArray);
?>
<?php for($i = 1; $i <= $cntArray; $i++): ?>
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="center-block">
                <div class="table-responsive">
                    <form action="" class="form-inline">
                        <table class="smarty table table-bordered">
                                <?php $cntEx = $smarty_examples->rows + 1?>
                                <?php foreach ($manyArOne as $k => $tr): ?>
                                    <?= $tr ?>
                                    <?php
                                    unset($manyArOne[$k]);
                                    if (--$cntEx == 0) {
                                        break;
                                    }
                                    ?>
                                <?php endforeach; ?>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    <?php if ($i != $cntArray && $smarty_examples->rows > 10): ?>
        <pagebreak />
    <?php endif; ?>
<?php endfor; ?>

yii2/frontend/views/simulator/abacus_html.php
<div id="wrap_abacus">
	<div id="abacus">
	
		<?php //if( ($_GET["lev"] == 1) || ($_GET["lev"] == 3) ) { ?>  <?php //} ?>
		<div id="itogo">0</div>
		
		<div id="reset_btn"></div>

		<div id="bead_up_1" class="bead upper_beads row_up col1 dragElement ui-widget ui-corner-all ui-state-error" data-val="5000"></div>
		<div id="bead_up_2" class="bead upper_beads row_up col2 dragElement ui-widget ui-corner-all ui-state-error" data-val="500"></div>
		<div id="bead_up_3" class="bead upper_beads row_up col3 dragElement ui-widget ui-corner-all ui-state-error" data-val="50"></div>
		<div id="bead_up_4" class="bead upper_beads row_up col4 dragElement ui-widget ui-corner-all ui-state-error" data-val="5"></div>

		<!-- beam -->
		<div id="bead_1_1" class="bead lower_beads row1 col1 dragElement ui-widget ui-corner-all ui-state-error" data-val="1000"></div>
		<div id="bead_1_2" class="bead lower_beads row1 col2 dragElement ui-widget ui-corner-all ui-state-error" data-val="100"></div>
		<div id="bead_1_3" class="bead lower_beads row1 col3 dragElement ui-widget ui-corner-all ui-state-error" data-val="10"></div>
		<div id="bead_1_4" class="bead lower_beads row1 col4 dragElement ui-widget ui-corner-all ui-state-error" data-val="1"></div>
		
		<div id="bead_2_1" class="bead lower_beads row2 col1 dragElement ui-widget ui-corner-all ui-state-error" data-val="1000"></div>
		<div id="bead_2_2" class="bead lower_beads row2 col2 dragElement ui-widget ui-corner-all ui-state-error" data-val="100"></div>
		<div id="bead_2_3" class="bead lower_beads row2 col3 dragElement ui-widget ui-corner-all ui-state-error" data-val="10"></div>
		<div id="bead_2_4" class="bead lower_beads row2 col4 dragElement ui-widget ui-corner-all ui-state-error" data-val="1"></div>
		
		<div id="bead_3_1" class="bead lower_beads row3 col1 dragElement ui-widget ui-corner-all ui-state-error" data-val="1000"></div>
		<div id="bead_3_2" class="bead lower_beads row3 col2 dragElement ui-widget ui-corner-all ui-state-error" data-val="100"></div>
		<div id="bead_3_3" class="bead lower_beads row3 col3 dragElement ui-widget ui-corner-all ui-state-error" data-val="10"></div>
		<div id="bead_3_4" class="bead lower_beads row3 col4 dragElement ui-widget ui-corner-all ui-state-error" data-val="1"></div>
		
		<div id="bead_4_1" class="bead lower_beads row4 col1 dragElement ui-widget ui-corner-all ui-state-error" data-val="1000"></div>
		<div id="bead_4_2" class="bead lower_beads row4 col2 dragElement ui-widget ui-corner-all ui-state-error" data-val="100"></div>
		<div id="bead_4_3" class="bead lower_beads row4 col3 dragElement ui-widget ui-corner-all ui-state-error" data-val="10"></div>
		<div id="bead_4_4" class="bead lower_beads row4 col4 dragElement ui-widget ui-corner-all ui-state-error" data-val="1"></div>
		
		<!--
		<div class="container_bead">
			<div id="up_bead_1" class="bead upper_beads row_up col1" data-val="5000"></div>
			<div class="bead lower_beads row1 col1" data-val="1000"></div>
			<div class="bead lower_beads row2 col1" data-val="1000"></div>
			<div class="bead lower_beads row3 col1" data-val="1000"></div>
			<div class="bead lower_beads row4 col1" data-val="1000"></div>
		</div>
		
		<div class="container_bead">
			<div class="bead upper_beads row_up col2" data-val="500"></div>
			<div class="bead lower_beads row1 col2" data-val="100"></div>
			<div class="bead lower_beads row2 col2" data-val="100"></div>
			<div class="bead lower_beads row3 col2" data-val="100"></div>
			<div class="bead lower_beads row4 col2" data-val="100"></div>
		</div>
		
		<div class="container_bead">
			<div class="bead upper_beads row_up col3" data-val="50"></div>
			<div class="bead lower_beads row1 col3" data-val="10"></div>
			<div class="bead lower_beads row2 col3" data-val="10"></div>
			<div class="bead lower_beads row3 col3" data-val="10"></div>
			<div class="bead lower_beads row4 col3" data-val="10"></div>
		</div>
		
		<div class="container_bead">
			<div class="bead upper_beads row_up col4" data-val="5"></div>
			<div class="bead lower_beads row1 col4" data-val="1"></div>
			<div class="bead lower_beads row2 col4" data-val="1"></div>
			<div class="bead lower_beads row3 col4" data-val="1"></div>
			<div class="bead lower_beads row4 col4" data-val="1"></div>
		</div>
		-->
		
	</div>
</div>

yii2/frontend/views/simulator/high-score.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 03.09.2018
 * Time: 15:24
 *
 * @var $this \yii\web\View
 * @var $high_scores \frontend\models\SimulatorsResults;
 * @var $errorMessage string
 */

use yii\helpers\Html;

$this->title = 'Smarty';
$this->params['breadcrumbs'][] = ['label' => 'Рекорды', 'url' => \yii\helpers\Url::to(['lk/records'])];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="page-header">
    <h1><?= Html::encode($this->title) ?> <small>Рекордсмены упражнения: Smarty (<?=$errorMessage?>)</small></h1>
</div>
<?php if($high_scores):?>
    <div class="responsive-table">
        <table class="table table-bordered">
            <tr>
                <th>Место</th>
                <th>ФИО</th>
                <th>Город</th>
                <th>Дата</th>
                <th>Результат</th>
            </tr>
            <?php
            $place = 1;
            ?>
            <?php foreach ($high_scores as $high_score): ?>
                <tr>
                    <?php
                    $color = '#fff';
                    if ($place == 1) $color = '#ffd700';
                    if ($place == 2) $color = '#b5b5bd';
                    if ($place == 3) $color = '#8c8752';
                    ?>
                    <td>
                        <?php if($place == 1 || $place == 2 || $place == 3): ?>
                            <span class="label" style="background-color: <?=$color?>"><?=$place++?></span>
                        <?php else: ?>
                            <?=$place++?>
                        <?php endif; ?>
                    </td>
                    <td><?=$high_score->user->fio?></td>
                    <td><?=$high_score->user->city?></td>
                    <td><?=Yii::$app->formatter->asDate($high_score->created_at, 'php: d.m.y')?></td>
                    <td><?=$high_score->time/1000?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
<?php endif; ?>

yii2/frontend/views/simulator/result.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 22.08.2018
 * Time: 12:06
 *
 * @var $this \yii\web\View
 * @var $simulators_results \frontend\models\SimulatorsResults
 */

use kartik\rating\StarRating;

$this->title = 'Резултать задание';
?>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="center-block">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Результаты тренажер <?= $simulators_results->simulator->name ?></h3>
                </div>
                <div class="panel-body text-center">
                    <?= StarRating::widget([
                        'name' => 'rating_result',
                        'value' => $simulators_results->ratingStar,
                        'pluginOptions' => ['displayOnly' => true]
                    ]); ?>
                    <div><strong>Рейтинг:</strong><?= $simulators_results->rating?> </div>
                    <div><strong>Правильно:</strong><span class="text-success"> <?= $simulators_results->true_answers?></span> </div>
                    <div><strong>Ошибки:</strong><span class="text-danger"> <?= $simulators_results->count_errors?></span> </div>
                    <span><strong>Потрачено: </strong><?= Yii::$app->formatter->asDuration($simulators_results->time/1000)?>, <?=$simulators_results->time%1000?> миллисекунд</span>
                </div>
                <div class="panel-footer">
                    <nav aria-label="...">
                        <ul class="pager">
                            <?php
                            //nujno utochnit jobSetting
                            $jobSettingValue = '';
                            switch ($simulators_results->id_simulator) {
                                case 1: $jobSettingValue = 'numbers'; break;
                                case 2: $jobSettingValue = 'map'; break;
                                case 3: $jobSettingValue = 'slalom'; break;
                                case 4: $jobSettingValue = 'multiply'; break;
                                case 5: $jobSettingValue = 'division'; break;
                                case 6: $jobSettingValue = 'shulteNumbers'; break;
                                case 7: $jobSettingValue = 'shulteAbacus'; break;
                                case 8: $jobSettingValue = 'MentalMap'; break;
                            }
                            ?>
                            <?php if ($simulators_results->id_simulator == 9): ?>
                                <li><a href="<?= \yii\helpers\Url::to(['/simulator/settings', 'id_simulators' => 9]) ?>">Новое задание</a></li>
                            <?php else: ?>
                                <li><a href="/jobs/training?jobSetting=<?=$jobSettingValue?>">Новое задание</a></li>
                            <?php endif; ?>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

yii2/frontend/views/simulator/smarty.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 21.08.2018
 * Time: 3:04
 * @var $this \yii\web\View
 * @var $smarty_examples \frontend\models\Smarty
 * @var $examplesArray array
 * @var $examplesAnswersArray array
 * @var $t string
 */

use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use frontend\assets\SmartyAsset;

SmartyAsset::register($this);

$this->title = 'Тренажер - Smarty';

$cssSmarty = <<<CSS
td, th{
border: 2px solid black;
}
CSS;

$this->registerCss($cssSmarty);


?>
<nav aria-label="...">
    <ul class="pager">
        <?php if ( $t == 'simulator' ): ?>
            <li class="next"><a href="<?= Url::to(['/simulator/exercise-print', 'id_smarty' => $smarty_examples->id])?>"><span class="glyphicon glyphicon-print" aria-hidden="true"></span> Print</a></li>
        <?php endif; ?>
    </ul>
</nav>

<div class="page-header">
    <h2>Тренажер Smarty <small>Задание: <?= $smarty_examples->name ?></small></h2>
    <p>
        <strong>Потрачено: </strong><span id="durationElem" class="label label-info"></span>
    </p>
</div>

<?php
$manyArOne = [];
    $tmpArray = array_chunk($examplesArray, 20);

    $cnt = 0;
    $answer_id = 0;
    $cntTmpArray = count($tmpArray);
    for ($j = 0; $j < $cntTmpArray; $j++) {
        for ($i = 0; $i < $smarty_examples->rows; $i++) {
            $manyArOne[$cnt++] = '<tr><td>' . implode('</td><td>', ArrayHelper::getColumn($tmpArray[$j], $i)) . '</td></tr>';
        }

        $tmpCount = count($tmpArray[$j]);
        $helperString = '';
        for ($k = 0; $k < $tmpCount; $k++) {
            $helperString .= '<td>' . '<div class="form-group"><input type="text" data-answerid="'. $answer_id++ .'" class="form-control example-answer"></div>' . '</td>';
        }
        $manyArOne[$cnt++] = '<tr>' . $helperString . '</tr>';
    }
?>
<div class="row">
    <div class="col-md-12">
        <div id="smartyTable" class="center-block" style="display: none;">
            <div class="table-responsive">
                <table class="smarty table table-bordered">
                    <?php foreach ($manyArOne as $tr): ?>
                        <?= $tr ?>
                    <?php endforeach; ?>
                </table>
            </div>
            <div class="center-block">
                <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary center-block', 'id' => 'smartySendButton']) ?>
                <div class="row">
                    <div class="col-md-2 col-md-offset-5">
                        <div class="progress"  style="display: none">
                            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                <span class="sr-only">45% Complete</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Modal-->
<div class="modal" id="startModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <!--<div class="modal-header">
                <h4 class="modal-title">Нажмите кнопку "START"</h4>
            </div>-->
            <div class="modal-body">
                <span id="countdownText"></span>
            </div><!--
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>-->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="id_user" data-val="<?=Yii::$app->session->get('login_user')?>"></div>
<div id="id_exercise" data-val="<?=$id_exercise?>"></div>
<div id="course_type" data-val="<?=$t?>"></div>
<div id="examplesAnswers" data-val="<?= json_encode($examplesAnswersArray)?>"></div>
<div id="id_smarty" data-val="<?= $smarty_examples->id?>"></div>