yii2/frontend/controllers/PackageController.php
<?php

namespace frontend\controllers;

use frontend\components\filters\AccessAdminFilter;
use frontend\components\filters\AccessUserFilter;
use frontend\models\package\PackageTheme;
use frontend\models\package\SelectUser;
use frontend\models\User;
use Yii;
use frontend\models\package\Package;
use frontend\models\package\PackageSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PackageController implements the CRUD actions for Package model.
 */
class PackageController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access-user' => [
                'class' => AccessUserFilter::class,
                'only' => ['franchise', 'partner'],
            ],
            'access-admin' => [
                'class' => AccessAdminFilter::class,
                'only' => ['index', 'view', 'delete', 'update', 'select-user']
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    //dlya sozdaniy tematika dlya paketa
    public function actionCreatePackageTheme() {
        $newTheme = new PackageTheme();

        if ($newTheme->load(Yii::$app->request->post()) && $newTheme->validate()) {
            if ($newTheme->save(false)) {

                Yii::$app->session->setFlash('success', 'Тема создан.');

                return $this->goBack();
            }
        }

        return $this->render('create-package-theme', [
            'newTheme' => $newTheme,
        ]);
    }

    public function actionSelectUser() {
        $model = new SelectUser();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->addUserInPackage();

                Yii::$app->session->addFlash('success', '<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Сделано!');
            return $this->redirect('index');
        }

        $userIDs = User::find()->select('fio')->indexBy('id')->column();
//        var_dump($userIDs);
//        exit;

        return $this->render('select-user', [
            'model' => $model,
            'userIDs' => $userIDs,
        ]);
    }

    public function actionFranchise(){
        $franchises = Package::find()
            ->where(['type' => 'franchise'])
            ->orderBy([
                'theme' => SORT_ASC,
            ])
            ->all();
        $user_id = Yii::$app->session->get('login_user');

        $buttons = [];
        foreach ($franchises as $franchise) {
            $publicIDs = unserialize($franchise->public_users);
            if (in_array($user_id, $publicIDs)) {
                $buttons[] = $franchise;
            }
        }

        return $this->render('franchise', [
            'buttons' => $buttons,
        ]);
    }

    public function actionPartner(){
        $partners = Package::find()
            ->where(['type' => 'partner'])
            ->orderBy([
                'theme' => SORT_ASC,
            ])
            ->all();
        $user_id = Yii::$app->session->get('login_user');

        $buttons = [];
        foreach ($partners as $partner) {
            $publicIDs = unserialize($partner->public_users);
            if (in_array($user_id, $publicIDs)) {
                $buttons[] = $partner;
            }
        }

        return $this->render('partner', [
            'buttons' => $buttons,
        ]);
    }

    /**
     * Lists all Package models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PackageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Package model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Package model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Package();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if ($model->saveAll()) {

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        $userIDs = User::find()->select(['fio'])->asArray()->indexBy('id')->column();

        return $this->render('create', [
            'model' => $model,
            'userIDs' => $userIDs
        ]);
    }

    /**
     * Updates an existing Package model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if ($model->saveAll()) {

                //Yii::$app->session->addFlash('success', 'Сделано');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        $userIDs = User::find()->select(['fio'])->asArray()->indexBy('id')->column();

        $package = Package::findOne($id);
        $publicIDs = unserialize($package->public_users);

        $selected_IDs = [];
        foreach ( $publicIDs as $publicID) {
            $selected_IDs[$publicID] = ['selected' => true];
        }

        return $this->render('update', [
            'model' => $model,
            'userIDs' => $userIDs,
            'selected_IDs' => $selected_IDs,
        ]);
    }

    /**
     * Deletes an existing Package model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Package model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Package the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Package::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /* ajax, dlya DepDrop, vivodit subkategoriya */
    public function actionGetThemes() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $package_name = $parents[0];
                $selected = '';
                if (isset($_POST['depdrop_all_params']['model-theme-id'])) {
                    $selected = $_POST['depdrop_all_params']['model-theme-id'];
                }
                $out = self::getGetThemeList($package_name);
                // the getSubCatList function will query the database based on the
                // cat_id and return an array like below:
                // [
                //    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
                //    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
                // ]

                //$selected = '';//self::getDefaultThemeName($package_theme_id);
                // the getDefaultSubCat function will query the database
                // and return the default sub cat for the cat_id
                //Yii::debug($out);
                return Json::encode(['output'=> $out, 'selected'=>$selected]);
                //return;
            }
        }
        return Json::encode(['output'=>'', 'selected'=>'']);
    }

    /*dlya Subcat, return Lesson list*/
    public static function getGetThemeList($package_name) {

        $themes = PackageTheme::find()->select(['id', 'name'])->where(['package_name' => $package_name])->all();
        $data = ArrayHelper::toArray($themes, [
            'frontend\models\package\PackageTheme' => [
                'id',
                'name',
            ]
        ]);
        return $data;
    }

    /*dlya subkategoriy, */
    public static function getDefaultThemeName($package_theme_id) {


    }
}

yii2/frontend/views/package/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model frontend\models\package\Package */
/* @var $userIDs array */
/* @var $form yii\widgets\ActiveForm */
/* @var $selected_IDs array */

$selected_IDs = isset($selected_IDs) ? $selected_IDs : [];
?>

<div class="package-form col-md-7">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'url')->hint('http:// или https://')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'type')->dropDownList([ 'franchise' => 'Франчайзинговый пакет', 'partner' => 'Партнерский пакет', ], ['prompt' => 'Выберите...', 'id' => 'package_parent']) ?>

    <?php
    // Additional input fields passed as params to the child dropdown's pluginOptions
    if (!$model->isNewRecord) echo Html::hiddenInput('model-theme-id', $model->theme, ['id'=>'model-theme-id']);
    ?>

    <?= $form->field($model, 'theme')->hint('Чтобы создать новый тематика: Напишите <strong>название</strong> и нажмите <kbd>Enter</kbd> или <kbd>Пробел</kbd>')->widget(DepDrop::class, [
        'type' => DepDrop::TYPE_SELECT2,
        'select2Options' => [
            'pluginOptions'=>[
                'allowClear' => true,
                'tags' => true,
                'tokenSeparators' => [',', ' '],
                'maximumInputLength' => 255,
            ],
        ],
        'options' => ['id'=>'theme-id'],
        'pluginOptions'=>[
            'tags' => true,
            'depends'=>['package_parent'],
            'placeholder' => 'Выберите...',
            'url' => Url::to(['/package/get-themes']),
            'params' => ['model-theme-id'],
            'initialize' => ($model->isNewRecord ? false : true),
            'initDepends'=>['package_parent'],
        ],
    ]); ?>

    <?= $form->field($model, 'public_users')->widget(Select2::class,[
        'name' => 'kv-state-240',
        'data' => $userIDs,
        'theme' => Select2::THEME_KRAJEE,
        'size' => Select2::MEDIUM,
        'options' => [
            'placeholder' => 'Выберите ...',
            'multiple' => true,
            'options' => $selected_IDs
        ],
        'pluginOptions' => [
            //'allowClear' => true
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii2/frontend/views/package/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\package\PackageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="package-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'url') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'public_users') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii2/frontend/views/package/create-package-theme.php
<?php
/**
 * @var $this \yii\web\View
 * @var $newTheme \frontend\models\package\PackageTheme
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Тематика';
$this->params['breadcrumbs'][] = ['label' => 'Все пакеты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="create-package-theme">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($newTheme, 'name')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii2/frontend/views/package/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\package\Package */
/* @var $userIDs array */

$this->title = 'Создать пакет';
$this->params['breadcrumbs'][] = ['label' => 'Все пакеты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="package-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'userIDs' => $userIDs
    ]) ?>

</div>

yii2/frontend/views/package/franchise.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 29.08.2018
 * Time: 0:15
 *
 * @var $this \yii\web\View
 * @var $buttons array
 */

use yii\helpers\Url;

$this->title = 'Франчайзинговый пакет';
?>
<div class="page-header">
    <h2>Франчайзинговый пакет</h2>
</div>

<?php if($buttons): ?>
    <div class="col-md-5">
        <div class="list-group">
            <?php foreach ($buttons as $button): ?>
                <a href="<?=Url::to($button->url)?>" target="_blank" class="list-group-item"><strong><?=\yii\helpers\Html::encode($button->name)?></strong></a>
            <?php endforeach; ?>
        </div>
    </div>
<?php else: ?>
    <div class="alert alert-danger" role="alert"><h3><strong>У вас недостаточно прав для доступа!</strong></h3></div>
<?php endif; ?>

yii2/frontend/views/package/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\package\PackageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Все пакеты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="package-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать пакет', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Выбрать пользователя', ['select-user'], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'name',
            'url:url',
            //'type',
            [
                'attribute' => 'type',
                'value' => 'package',
                'filter' => [
                    'partner' => 'Партнерский пакет',
                    'franchise' => 'Франчайзинговый пакет'
                ],
                'filterInputOptions' => [
                    'prompt' => 'Все пакеты',
                    'class' => 'form-control',
                ]
            ],
            [
                'attribute' => 'theme',
                'value' => function($model) {
                    return ($value = $model->getThemeName()) === false ? '<span class="text-danger">Не задано</span>' : $value;
                },
                'format' => 'raw',
                'filter' => \frontend\models\package\PackageTheme::getThemes(),
                'filterInputOptions' => [
                    'prompt' => 'Все тематика',
                    'class' => 'form-control',
                ]
            ],
            //'public_users',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

yii2/frontend/views/package/partner.php
<?php
/**
 * Created by PhpStorm.
 * User: Javlonbek
 * Date: 29.08.2018
 * Time: 0:15
 *
 * @var $this \yii\web\View
 * @var $buttons array
 */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Партнерский пакет';
?>
<div class="page-header">
    <h2>Партнерский пакет</h2>
</div>

<?php if($buttons): ?>
    <div class="col-md-5">
        <div class="list-group">
            <?php foreach ($buttons as $button): ?>
                <a href="<?=Url::to($button->url)?>" target="_blank" class="list-group-item"><strong><?=Html::encode($button->name)?></strong></a>
            <?php endforeach; ?>
        </div>
    </div>
<?php else: ?>
    <div class="alert alert-danger" role="alert"><h3><strong>У вас недостаточно прав для доступа!</strong></h3></div>
<?php endif; ?>

yii2/frontend/views/package/select-user.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;


/* @var $this yii\web\View */
/* @var $model frontend\models\package\Package */
/* @var $userIDs array */

$this->title = 'Выбрать пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Все пакеты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="package-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="select-user-form col-md-7">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'user')->widget(Select2::class,[
            'name' => 'select-user',
            'data' => $userIDs,
            'theme' => Select2::THEME_KRAJEE,
            'size' => Select2::MEDIUM,
            'options' => [
                'placeholder' => 'Выберите ...',
            ],
            'pluginOptions' => [
                //'allowClear' => true
            ],
        ]) ?>

        <?= $form->field($model, 'franchisePackage')->checkbox() ?>
        <?= $form->field($model, 'partnerPackage')->checkbox() ?>

        <div class="form-group">
            <?= Html::submitButton('Дать доступ', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

yii2/frontend/views/package/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\package\Package */
/* @var $userIDs array */
/* @var $selected_IDs array */

$this->title = "Обновить пакет: {$model->name}";
$this->params['breadcrumbs'][] = ['label' => 'Все пакеты', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>
<div class="package-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'userIDs' => $userIDs,
        'selected_IDs' => $selected_IDs,
    ]) ?>

</div>

yii2/frontend/views/package/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\package\Package */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Все пакеты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="package-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить этот элемент?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            'name',
            'url:url',
            //'type',
            [
                'attribute' => 'type',
                'value' => $model->getPackage(),
            ],
            [
                'attribute' => 'theme',
                'value' => ($value = $model->getThemeName()) === false ? '<span class="text-danger">Не задано</span>' : $value,
                'format' => 'raw',
            ],
            //'public_users',
            ['attribute' => 'public_users', 'format' => 'html', 'value' => function($model,$widget) {
                $users = $model->users;
                $html = '<ul class="list-group">';
                foreach($users as $user) {
                    $html .= '<li class="list-group-item">';
                    $html .= '<span class="badge">';
                    $html .= $user->type;
                    $html .= '</span>';
                    $html .= $user->fio;
                    $html .= '</li>';
                }
                $html .= '</ul>';

                return $html;
            }]
        ],
    ]) ?>

</div>